<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/Transaction/ValidationOrder/coherenceGet" name="coherenceGet-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="coherenceGet.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/Transaction/ValidationOrder/coherenceGet"/>
    <wsdl:binding name="Get_ptt-binding" type="coh:Get_ptt" xmlns:coh="http://xmlns.oracle.com/pcbpel/adapter/coherence/Transaction/ValidationOrder/coherenceGet">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Get">
            <soap:operation soapAction="Get"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>