<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/Transaction/ValidationOrder/coherencePut" name="coherencePut-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="coherencePut.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/coherence/Transaction/ValidationOrder/coherencePut"/>
    <wsdl:binding name="Put_ptt-binding" type="coh:Put_ptt" xmlns:coh="http://xmlns.oracle.com/pcbpel/adapter/coherence/Transaction/ValidationOrder/coherencePut">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Put">
            <soap:operation soapAction="Put"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>